const I18N={
en:{navAtlas:"Atlas",navCases:"Case studies",navModels:"Operating models",navEcosystem:"Ecosystem",heroEyebrow:"ALMOND INTELLIGENCE / SAUDI ARABIA",heroLine1:"Good intentions.",heroLine2:"Mapped impact.",heroIntro:"A living research atlas of Saudi Arabia's corporate social responsibility ecosystem — from philanthropy to purpose-led innovation.",explore:"Explore the atlas",methodology:"Read methodology",statInitiatives:"verified initiatives",statCompanies:"registered companies",statModels:"operating models",statValue:"SAR documented value",scroll:"SCROLL TO EXPLORE",statementKicker:"THE REAL PICTURE",statementTitle:"Saudi CSR is not one market. It is two worlds moving closer together.",world1Title:"Corporate CSR & ESG",world1Text:"Long-term programs, partnerships and measurable social outcomes.",overlap:"THE OVERLAP IS THE OPPORTUNITY",world2Title:"Purpose-driven marketing",world2Text:"Public-facing campaigns that turn social issues into participation and cultural change.",atlasKicker:"THE RESEARCH UNIVERSE",atlasTitle:"50 documented initiatives.<br>One explorable atlas.",atlasNote:"Search by company, initiative or operator. Filter by the model of impact.",search:"Search company, initiative or operator…",clear:"Clear filters",loadMore:"Load more initiatives",casesKicker:"SIGNAL, NOT NOISE",casesTitle:"Five cases that changed the shape of impact.",casesIntro:"Selected for strategic depth, measurable outcomes and a model others can learn from.",modelsKicker:"EIGHT WAYS IMPACT HAPPENS",modelsTitle:"The Saudi CSR operating model.",modelsNote:"The strongest programs connect a social need, an organizational capability and a credible implementation partner.",ecoKicker:"WHO MAKES IT HAPPEN",ecoTitle:"A network, not a vendor list.",ecoText:"Saudi CSR is delivered by creative agencies, government platforms, nonprofits, hospitals, universities and volunteer networks. The operator depends on the impact model.",closingKicker:"ALMOND / IMPACT INTELLIGENCE",closingTitle:"The next meaningful campaign starts with understanding the system.",talk:"Start a conversation",footerText:"Saudi CSR Atlas · Research edition 2026",backTop:"Back to top ↑",methodKicker:"RESEARCH METHOD",methodTitle:"Verified, attributed, and honest about its limits.",methodText1:"This atlas is a curated research universe of publicly documented Saudi CSR initiatives. It does not claim to contain every CSR activity ever conducted in the Kingdom.",methodText2:"Initiatives are included when supported by official company reporting, government sources, Saudi Exchange filings, award databases or documented campaign case studies. Agency attribution appears only when explicitly credited.",verified:"Verified sources",attributed:"Clear attribution",updated:"2026 research",all:"All",results:"initiatives found",operator:"Operator / implementation",impact:"Impact / location",model:"Operating model",view:"View initiative"},
ar:{navAtlas:"الأطلس",navCases:"دراسات الحالة",navModels:"نماذج التشغيل",navEcosystem:"المنظومة",heroEyebrow:"أبحاث ألموند / المملكة العربية السعودية",heroLine1:"نوايا تصنع الخير.",heroLine2:"أثر يمكن قياسه.",heroIntro:"أطلس بحثي تفاعلي لمنظومة المسؤولية الاجتماعية في السعودية — من العطاء الخيري إلى الابتكار الهادف.",explore:"استكشف الأطلس",methodology:"اقرأ المنهجية",statInitiatives:"مبادرة موثقة",statCompanies:"شركة مسجلة",statModels:"نماذج تشغيل",statValue:"ريال قيمة موثقة",scroll:"مرّر للاستكشاف",statementKicker:"الصورة الحقيقية",statementTitle:"المسؤولية الاجتماعية السعودية ليست سوقاً واحدة، بل عالمان يقتربان من بعضهما.",world1Title:"المسؤولية المؤسسية والاستدامة",world1Text:"برامج طويلة المدى وشراكات ونتائج اجتماعية قابلة للقياس.",overlap:"في نقطة الالتقاء تكمن الفرصة",world2Title:"التسويق الهادف",world2Text:"حملات عامة تحوّل القضايا الاجتماعية إلى مشاركة وتغيير ثقافي.",atlasKicker:"عالم البحث",atlasTitle:"50 مبادرة موثقة.<br>أطلس واحد قابل للاستكشاف.",atlasNote:"ابحث باسم الشركة أو المبادرة أو المشغّل، وصفِّ النتائج حسب نموذج الأثر.",search:"ابحث عن شركة أو مبادرة أو مشغّل…",clear:"مسح التصفية",loadMore:"عرض مبادرات إضافية",casesKicker:"إشارات تستحق الانتباه",casesTitle:"خمس حالات أعادت تشكيل مفهوم الأثر.",casesIntro:"اخترناها لعمقها الاستراتيجي ونتائجها القابلة للقياس وإمكانية التعلم منها.",modelsKicker:"ثماني طرق لصناعة الأثر",modelsTitle:"نموذج تشغيل المسؤولية الاجتماعية السعودي.",modelsNote:"تربط أقوى البرامج بين حاجة اجتماعية وقدرة مؤسسية وشريك تنفيذ موثوق.",ecoKicker:"من يحوّل الفكرة إلى واقع؟",ecoTitle:"شبكة متكاملة، وليست قائمة مورّدين.",ecoText:"تنفذ المسؤولية الاجتماعية في السعودية وكالات إبداعية ومنصات حكومية ومنظمات غير ربحية ومستشفيات وجامعات وشبكات تطوعية، ويحدد نموذج الأثر الشريك الأنسب.",closingKicker:"ألموند / استخبارات الأثر",closingTitle:"الحملة المؤثرة التالية تبدأ بفهم المنظومة.",talk:"ابدأ محادثة",footerText:"أطلس المسؤولية الاجتماعية السعودي · إصدار 2026",backTop:"العودة للأعلى ↑",methodKicker:"منهجية البحث",methodTitle:"موثّق، واضح النسب، وصريح بشأن حدوده.",methodText1:"هذا الأطلس عالم بحثي منسق لمبادرات المسؤولية الاجتماعية السعودية الموثقة علناً، ولا يدّعي احتواء كل نشاط نُفّذ في المملكة.",methodText2:"تُدرج المبادرات عند دعمها بتقارير الشركات الرسمية أو المصادر الحكومية أو إفصاحات تداول أو قواعد الجوائز أو دراسات الحملات. ولا تُنسب الوكالة إلا عند وجود توثيق صريح.",verified:"مصادر موثقة",attributed:"نسب واضح",updated:"بحث 2026",all:"الكل",results:"مبادرة مطابقة",operator:"المشغّل / جهة التنفيذ",impact:"الأثر / الموقع",model:"نموذج التشغيل",view:"عرض المبادرة"}
};

const cats={philanthropy:{en:"Philanthropy",ar:"العطاء الخيري"},community:{en:"Community service",ar:"خدمة المجتمع"},environment:{en:"Environment",ar:"البيئة"},education:{en:"Education & youth",ar:"التعليم والشباب"},inclusion:{en:"Inclusion",ar:"الدمج"},digital:{en:"Digital CSR",ar:"المسؤولية الرقمية"},purpose:{en:"Purpose marketing",ar:"التسويق الهادف"},embedded:{en:"Embedded impact",ar:"الأثر المدمج"}};
const D=(company,name,arName,category,idea,arIdea,operator,impact)=>({company,name,arName,category,idea,arIdea,operator,impact});
const initiatives=[
D("Aramco","Coffee Initiative","مبادرة القهوة",'community',"Develop Saudi coffee production while improving farmers' income, productivity and water efficiency.","تطوير إنتاج البن السعودي ورفع دخل المزارعين وإنتاجيتهم وكفاءة استخدام المياه.","Aramco + Jazan Mountains Development Authority + Al-Dayer Charitable Society","Jazan & Asir · 1,057 farmers · 203,000 seedlings"),
D("Aramco","Drones vs Desertification","الطائرات المسيّرة ضد التصحر",'purpose',"Use drones and public participation to plant native trees and make environmental action visible.","استخدام الطائرات المسيّرة والمشاركة العامة لزراعة الأشجار المحلية وإبراز العمل البيئي.","Aramco + Leo Burnett","Saudi Arabia · Environmental sustainability"),
D("Aramco","Volunteer Program","برنامج التطوع",'community',"Institutionalize employee and community volunteering at scale.","مأسسة تطوع الموظفين والمجتمع على نطاق واسع.","Aramco + KFUPM AlFozan Academy + nonprofit partners","160,457 volunteers · 1.48M hours in 2025"),
D("stc","Give More","عطاء أكثر",'purpose',"Ramadan platform connecting generosity, sustainability and a better future.","منصة رمضانية تربط العطاء والاستدامة بمستقبل أفضل.","stc + UM + Snapchat · Kantar measurement","Nationwide · 13.9% incremental reach over TV"),
D("Mobily","Treat It as Your Guest","عامله كضيفك",'purpose',"Teach children how to recognize and avoid cyberbullying.","تعليم الأطفال كيفية التعرف على التنمر الإلكتروني وتجنبه.","Mobily + community activation","Social media + workshop · 25 children"),
D("Mobily","Saudi Environmental Week","أسبوع البيئة السعودي",'environment',"Promote environmental protection and the Saudi Green Initiative.","تعزيز حماية البيئة ومبادرة السعودية الخضراء.","Mobily + Ministry of Environment, Water & Agriculture","Nationwide"),
D("Mobily","Ambassadors of Giving","سفراء العطاء",'community',"Volunteer support for pilgrims' safety and wellbeing during Hajj.","دعم تطوعي لسلامة الحجاج ورفاههم خلال موسم الحج.","Mobily + Saudi Red Crescent Authority","Hajj · Pilgrim support"),
D("SABIC","Saudi CSR Portfolio","محفظة المسؤولية الاجتماعية",'community',"Integrated programs spanning health, food security, education and the environment.","برامج متكاملة تشمل الصحة والأمن الغذائي والتعليم والبيئة.","SABIC + Ehsan + Injaz Saudi Arabia + public partners","Nationwide"),
D("SABIC","STEM & Sustainability Education","تعليم العلوم والاستدامة",'education',"Develop sustainability and leadership skills among school students.","تنمية مهارات الاستدامة والقيادة لدى طلاب المدارس.","SABIC + Injaz Saudi Arabia","939 schools · 16 cities · 58,652 students"),
D("SABIC","Ehsan Contribution","المساهمة في إحسان",'philanthropy',"Fund social responsibility programs through the national giving platform.","تمويل برامج المسؤولية الاجتماعية عبر المنصة الوطنية للعمل الخيري.","SABIC + Ehsan","SAR 10M in 2025"),
D("Bank Albilad","Environmental Awareness Campaign","حملة الوعي البيئي",'environment',"Mobilize volunteers to collect waste and promote environmental responsibility.","حشد المتطوعين لجمع النفايات وتعزيز المسؤولية البيئية.","Bank Albilad volunteer team + community partners","King Salman Park · 1+ ton collected"),
D("Bank Albilad","Jood Housing Contribution","مساهمة جود الإسكان",'philanthropy',"Help families in need access adequate housing.","مساعدة الأسر الأشد حاجة في الحصول على السكن الملائم.","Bank Albilad + Jood","SAR 10M · 5,250 families"),
D("Bank Albilad","Pilgrims Gift","هدية البلاد للحجاج",'community',"Provide sunshades that improve pilgrims' comfort and safety.","توفير مظلات شمسية لتحسين راحة الحجاج وسلامتهم.","Bank Albilad","Hajj 2024"),
D("Bank Albilad","Ramadan Basket","السلة الرمضانية",'philanthropy',"Provide food and essential support to families in need.","توفير الغذاء والدعم الأساسي للأسر المحتاجة.","Bank Albilad + community organizations","29,000+ beneficiaries"),
D("Al Rajhi Bank","Quick Donation","التبرع السريع",'digital',"Turn the banking app into a frictionless, scalable channel for charitable giving.","تحويل التطبيق المصرفي إلى قناة سهلة وقابلة للتوسع للتبرع الخيري.","Al Rajhi Bank + 1,700+ nonprofits + Ehsan/Jood","SAR 2.7B facilitated by end-2024"),
D("Al Rajhi Bank","Anti-fraud Hajj Campaign","حملة مكافحة الاحتيال في الحج",'purpose',"Protect pilgrims by raising awareness of financial fraud.","حماية الحجاج عبر التوعية بمخاطر الاحتيال المالي.","Al Rajhi CSR + Marketing teams","Hajj pilgrims"),
D("Al Rajhi Bank","Wise Banker","المصرفي الواعي",'education',"Build financial literacy among university students.","بناء الوعي المالي لدى طلاب الجامعات.","Al Rajhi Bank + Prince Sultan University","Students"),
D("McDonald's Saudi Arabia","Share the Goodness","شارك الخير",'community',"Deliver essential home appliances to families during Ramadan.","توفير الأجهزة المنزلية الأساسية للأسر خلال رمضان.","Saudi licensees + Ehsan + charities + employee volunteers","750+ families · 1,000+ appliances · 10 cities"),
D("Nahdi Medical","Convoys of Hope","قوافل الأمل",'community',"Take healthcare services to communities with limited access.","إيصال الخدمات الصحية إلى المجتمعات محدودة الوصول للرعاية.","Nahdi + Al Hayat + Enaya + Al Ehsan NGOs","32,064 beneficiaries · 21 villages · 93 days"),
D("Tasnee","Social Contribution Portfolio","محفظة الإسهام الاجتماعي",'philanthropy',"Support food security, health, disability inclusion, orphans and volunteering.","دعم الأمن الغذائي والصحة ودمج ذوي الإعاقة والأيتام والتطوع.","Tasnee + nonprofit partners + Ehsan","5,000 Ramadan families · 110 year-round"),
D("Bawan","Targeted Community Interventions","مبادرات مجتمعية موجهة",'philanthropy',"Coordinate food, water, health and education interventions with specialist partners.","تنسيق مبادرات الغذاء والمياه والصحة والتعليم مع شركاء متخصصين.","Bawan + Eta'am + Ehsan + KSrelief + Health Endowments","Thousands of beneficiaries"),
D("OSUS Real Estate","Ehsan Endowment Partnership","شراكة وقف إحسان",'embedded',"Dedicate a defined contribution from every real-estate unit sold to endowments.","تخصيص مساهمة محددة من كل وحدة عقارية مباعة لصالح الأوقاف.","OSUS + Ehsan","Nationwide projects"),
D("Southern Province Cement","Green Footprint","البصمة الخضراء",'environment',"Deliver long-term tree planting and desertification mitigation.","تنفيذ برنامج طويل المدى للتشجير ومكافحة التصحر.","Southern Province Cement + community volunteers","Bisha · 500,000-tree target by 2030"),
D("MBC AL AMAL","Planting Roots — KSA","غرس الجذور — السعودية",'environment',"Restore vegetation through government partnership and volunteering.","استعادة الغطاء النباتي عبر شراكة حكومية ومشاركة تطوعية.","MBC AL AMAL + NCVC","Al Bahah · 400 trees · 70+ participants"),
D("Zain KSA","Liajlehum Partnership","شراكة لأجلهم",'inclusion',"Create accessible digital solutions and advance disability inclusion.","ابتكار حلول رقمية ميسرة وتعزيز دمج الأشخاص ذوي الإعاقة.","Zain KSA + Liajlehum Association","Nationwide"),
D("NHC","Wae'd Youth Program","برنامج واعد للشباب",'education',"Connect housing-sector growth with Saudi youth development.","ربط نمو قطاع الإسكان بتمكين الشباب السعودي.","NHC + training partners","500 trainees by 2025"),
D("ROSHN Group","Community Quality of Life","جودة الحياة المجتمعية",'community',"Combine housing support, charitable giving and elderly care.","الجمع بين دعم الإسكان والعطاء الخيري ورعاية كبار السن.","ROSHN + Ehsan + Jood + Kibar","Nationwide"),
D("SRMG","Community Media Support","الدعم الإعلامي المجتمعي",'purpose',"Use media reach to amplify charities, culture and social causes.","تسخير الانتشار الإعلامي لدعم الجمعيات والثقافة والقضايا الاجتماعية.","SRMG + charitable organizations","Saudi Arabia & region"),
D("Almarai","Community Impact Portfolio","محفظة الأثر المجتمعي",'community',"Advance environmental sustainability, wellbeing and economic opportunity.","تعزيز الاستدامة البيئية والرفاه والفرص الاقتصادية.","Almarai + community partners","50,000+ people reached"),
D("OMO / Unilever","The Art of Stains","فن البقع",'purpose',"Use Saudi henna culture to open a respectful conversation about menstrual stigma.","استخدام ثقافة الحناء السعودية لفتح حوار محترم حول وصمة الدورة الشهرية.","Unilever + MullenLowe MENA + Milkshake Media","Saudi women · 96.3% positive sentiment"),
D("Nova Water","Sustainability Campaign","حملة نوفا للاستدامة",'purpose',"Bring sustainability into consumer-facing brand communication.","دمج الاستدامة في التواصل الجماهيري للعلامة التجارية.","Nova + Mindshare KSA","Saudi Arabia"),
D("SYNC","The Sync-ervention","سينك-رفينشن",'purpose',"A social-impact intervention recognized for effective purpose marketing.","تدخل ذو أثر اجتماعي حاز تقديراً في التسويق الهادف.","SYNC","MMA SMARTIES KSA · Gold"),
D("Theeb Rent a Car","Breast Cancer Awareness","التوعية بسرطان الثدي",'purpose',"Support breast-cancer awareness and specialist nonprofit work.","دعم التوعية بسرطان الثدي وعمل الجمعيات المتخصصة.","Theeb + Zahra Association","Saudi Arabia"),
D("Chemanol","Drug Awareness Initiative","مبادرة التوعية بأضرار المخدرات",'purpose',"Educate employees about drug risks and prevention.","توعية الموظفين بمخاطر المخدرات وأساليب الوقاية.","Chemanol + General Directorate of Narcotics Control","Jubail · Employees"),
D("Chemanol","Sakha App","تطبيق سخاء",'digital',"Digitally enable and sustain charitable work in Jubail.","تمكين العمل الخيري رقمياً واستدامته في الجبيل.","Chemanol + Jubail Charitable Society","Five-year sponsorship"),
D("Chemanol","Blood Donation","حملة التبرع بالدم",'community',"Encourage employees to contribute to local blood supply.","تشجيع الموظفين على دعم مخزون الدم المحلي.","Chemanol + Saudi German Hospital","Headquarters"),
D("GIG Saudi","World Cancer Day","اليوم العالمي للسرطان",'community',"Combine blood donation, awareness and cancer-patient support.","الجمع بين التبرع بالدم والتوعية ودعم مرضى السرطان.","GIG Saudi + Sanad Society","Riyadh"),
D("GIG Saudi","Ramadan Iftar","إفطار رمضان",'philanthropy',"Distribute Iftar meals and strengthen community solidarity.","توزيع وجبات الإفطار وتعزيز التكافل المجتمعي.","GIG Saudi","Saudi communities"),
D("Burgerizzr","Child Health: A Better World","صحة الطفل: عالم أفضل",'purpose',"Use brand reach to build awareness around child health.","تسخير انتشار العلامة لرفع الوعي بصحة الطفل.","Burgerizzr","300,000+ campaign video reach"),
D("Burgerizzr","Our Children, Our Future","أطفالنا مستقبلنا",'community',"Support child-focused social responsibility activity.","دعم أنشطة المسؤولية الاجتماعية الموجهة للأطفال.","Burgerizzr","Saudi Arabia"),
D("SAUDI AZM","KSU Hackathon","هاكاثون جامعة الملك سعود",'education',"Improve students' innovation skills and employability.","تطوير مهارات الابتكار لدى الطلاب وتعزيز فرصهم المهنية.","SAUDI AZM + King Saud University","University students"),
D("SAUDI AZM","Business Analysis Competition","مسابقة تحليل الأعمال",'education',"Build analytical and management capability among students.","بناء القدرات التحليلية والإدارية لدى الطلاب.","SAUDI AZM + King Saud University","University students"),
D("MBC AL AMAL","Roots of Change","جذور التغيير",'environment',"Restore mangrove and terrestrial ecosystems through volunteer action.","استعادة النظم البيئية للمانغروف والغطاء النباتي عبر التطوع.","MBC AL AMAL + environmental partners","500 mangroves in 2025 + KSA expansion"),
D("Sipchem","Sipchem Cares","سبكيم تهتم",'community',"Build long-term partnerships across social and community priorities.","بناء شراكات طويلة المدى عبر أولويات اجتماعية ومجتمعية متعددة.","Sipchem + 30+ nonprofit and public partners","Nationwide"),
D("Sadara","Environmental Solutions Competition","مسابقة الحلول البيئية المبتكرة",'education',"Encourage environmental awareness and practical sustainability solutions.","تشجيع الوعي البيئي والحلول العملية للاستدامة.","Sadara","Saudi communities"),
D("SASREF","CSR Program","برنامج المسؤولية الاجتماعية",'community',"Coordinate environmental, governance and social initiatives.","تنسيق المبادرات البيئية والحوكمية والاجتماعية.","SASREF","Saudi Arabia"),
D("Saudi Electricity Company","CSR Portfolio","محفظة المسؤولية الاجتماعية",'community',"Support health, education, community development and sustainability.","دعم الصحة والتعليم وتنمية المجتمع والاستدامة.","SEC + nonprofit and public partners","Nationwide"),
D("ROSHN Group","National Charity Campaign","الحملة الوطنية للعمل الخيري",'philanthropy',"Make a major Ramadan contribution through the national giving infrastructure.","تقديم مساهمة رمضانية كبرى عبر البنية الوطنية للعمل الخيري.","ROSHN + Ehsan","SAR 30M"),
D("Al Othaim Markets","Community Contribution Portfolio","محفظة الإسهام المجتمعي",'community',"Combine volunteering, local employment and community development.","الجمع بين التطوع والتوظيف المحلي وتنمية المجتمع.","Al Othaim + community partners","Nationwide"),
D("MBC AL AMAL","KSA Environmental Expansion","التوسع البيئي في السعودية",'environment',"Engage local associations in vegetation restoration.","إشراك الجمعيات المحلية في استعادة الغطاء النباتي.","MBC AL AMAL + NCVC + six volunteer associations","Al Bahah")
];

const cases=[
{company:"Aramco",title:{en:"Coffee Initiative",ar:"مبادرة القهوة"},text:{en:"A multi-year economic-development program integrating farmer income, quality, production and water efficiency.",ar:"برنامج تنمية اقتصادية متعدد السنوات يدمج دخل المزارعين والجودة والإنتاج وكفاءة المياه."},metrics:[["1,057",{en:"farmers",ar:"مزارعاً"}],["203K",{en:"seedlings",ar:"شتلة"}],["80%",{en:"less water",ar:"خفض المياه"}]]},
{company:"Al Rajhi Bank",title:{en:"Quick Donation",ar:"التبرع السريع"},text:{en:"A banking feature transformed charitable giving into a scalable digital product used across the Kingdom.",ar:"ميزة مصرفية حوّلت العطاء الخيري إلى منتج رقمي قابل للتوسع في أنحاء المملكة."},metrics:[["SAR 2.7B",{en:"facilitated",ar:"تبرعات ميسرة"}],["1,700+",{en:"nonprofits",ar:"جهة غير ربحية"}],["17+",{en:"funds",ar:"صندوقاً وقفياً"}]]},
{company:"Nahdi Medical",title:{en:"Convoys of Hope",ar:"قوافل الأمل"},text:{en:"CSR built around core healthcare capability, reaching villages where access is limited.",ar:"مسؤولية اجتماعية مبنية على خبرة الرعاية الصحية للوصول إلى القرى محدودة الخدمات."},metrics:[["32,064",{en:"beneficiaries",ar:"مستفيداً"}],["21",{en:"villages",ar:"قرية"}],["93",{en:"operating days",ar:"يوم تشغيل"}]]},
{company:"OMO / Unilever",title:{en:"The Art of Stains",ar:"فن البقع"},text:{en:"A culturally fluent purpose campaign using henna to open conversation around menstrual stigma.",ar:"حملة هادفة متفهمة للثقافة استخدمت الحناء لفتح حوار حول وصمة الدورة الشهرية."},metrics:[["96.3%",{en:"positive sentiment",ar:"مشاعر إيجابية"}],["23%",{en:"sales increase",ar:"نمو المبيعات"}],["40%",{en:"social share rise",ar:"نمو المشاركة"}]]},
{company:"OSUS Real Estate",title:{en:"Impact in Every Sale",ar:"أثر في كل عملية بيع"},text:{en:"CSR is embedded into the commercial transaction: every sold unit contributes to endowment initiatives.",ar:"أثر مدمج في المعاملة التجارية: كل وحدة مباعة تساهم في مبادرات وقفية."},metrics:[["1",{en:"integrated model",ar:"نموذج مدمج"}],["Every",{en:"unit sold",ar:"وحدة مباعة"}],["Ehsan",{en:"implementation",ar:"شريك التنفيذ"}]]}
];

const models=[
['philanthropy',{en:"Philanthropic CSR",ar:"العطاء الخيري"},{en:"Money, resources and direct support.",ar:"تمويل وموارد ودعم مباشر."}],
['community',{en:"Community service",ar:"خدمة المجتمع"},{en:"The company physically provides a service.",ar:"تقدم الشركة خدمة فعلية للمجتمع."}],
['environment',{en:"Environmental CSR",ar:"المسؤولية البيئية"},{en:"Restoration, planting and resource efficiency.",ar:"استعادة وتشجير وكفاءة للموارد."}],
['education',{en:"Education & youth",ar:"التعليم والشباب"},{en:"Skills, leadership and employability.",ar:"مهارات وقيادة وفرص مهنية."}],
['inclusion',{en:"Inclusion",ar:"الدمج"},{en:"Accessibility and equitable participation.",ar:"إتاحة ومشاركة عادلة."}],
['digital',{en:"Digital CSR",ar:"المسؤولية الرقمية"},{en:"Technology that scales access and giving.",ar:"تقنية توسع الوصول والعطاء."}],
['purpose',{en:"Purpose-driven marketing",ar:"التسويق الهادف"},{en:"Public communication that shifts culture.",ar:"تواصل جماهيري يصنع تغييراً ثقافياً."}],
['embedded',{en:"Embedded impact",ar:"الأثر المدمج"},{en:"Social value built into every transaction.",ar:"قيمة اجتماعية داخل كل معاملة."}]
];
const operators=["Ehsan","Leo Burnett","MullenLowe MENA","UM","Mindshare KSA","Injaz Saudi Arabia","Saudi Red Crescent","NCVC","Jood","Eta'am","Sanad Society","Saudi German Hospital","King Saud University","KSrelief","Volunteer networks","Community NGOs"];

let lang='en',active='all',visible=12,casePosition=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const t=k=>I18N[lang][k]||k;
function setLanguage(next){lang=next;const ar=lang==='ar';document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';$$('[data-i18n]').forEach(el=>{el.innerHTML=t(el.dataset.i18n)});$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('.lang-switch').innerHTML=ar?'<span>EN</span><span class="lang-active">ع</span>':'<span class="lang-active">EN</span><span>ع</span>';renderFilters();renderInitiatives();renderCases();renderModels();}
function renderFilters(){const keys=['all',...Object.keys(cats)];$('#filters').innerHTML=keys.map(k=>`<button class="filter ${active===k?'active':''}" data-filter="${k}">${k==='all'?t('all'):cats[k][lang]}</button>`).join('');}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase();return initiatives.filter(x=>(active==='all'||x.category===active)&&(!q||[x.company,x.name,x.arName,x.idea,x.arIdea,x.operator,x.impact].join(' ').toLowerCase().includes(q)));}
function renderInitiatives(){const list=filtered();$('#resultCount').textContent=`${list.length} ${t('results')}`;$('#initiativeGrid').innerHTML=list.slice(0,visible).map((x,i)=>`<button class="initiative-card" data-index="${initiatives.indexOf(x)}" aria-label="${t('view')}: ${lang==='ar'?x.arName:x.name}"><div class="card-top"><span class="card-number">${String(initiatives.indexOf(x)+1).padStart(2,'0')}</span><span class="category-pill">${cats[x.category][lang]}</span></div><div class="company">${x.company}</div><h3>${lang==='ar'?x.arName:x.name}</h3><p>${lang==='ar'?x.arIdea:x.idea}</p><span class="card-arrow">↗</span></button>`).join('');$('#loadMore').hidden=visible>=list.length;}
function openDetail(i){const x=initiatives[i];$('#modalContent').innerHTML=`<p class="modal-company">${x.company} · ${cats[x.category][lang]}</p><h2>${lang==='ar'?x.arName:x.name}</h2><p class="modal-idea">${lang==='ar'?x.arIdea:x.idea}</p><div class="detail-grid"><div><span>${t('operator')}</span><strong>${x.operator}</strong></div><div><span>${t('impact')}</span><strong>${x.impact}</strong></div><div><span>${t('model')}</span><strong>${cats[x.category][lang]}</strong></div><div><span>Almond index</span><strong>#${String(i+1).padStart(2,'0')} / 50</strong></div></div>`;toggleModal('#detailModal',true);}
function toggleModal(id,open){const el=$(id);el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('modal-open',open);if(open)setTimeout(()=>el.querySelector('.modal-close').focus(),80);}
function renderCases(){const track=$('#caseTrack');track.innerHTML=cases.map((c,i)=>`<article class="case-card"><span class="case-label">CASE ${String(i+1).padStart(2,'0')} · ${c.company}</span><h3>${c.title[lang]}</h3><p>${c.text[lang]}</p><div class="case-metrics">${c.metrics.map(m=>`<div><strong>${m[0]}</strong><span>${m[1][lang]}</span></div>`).join('')}</div></article>`).join('');casePosition=0;moveCases();}
function moveCases(){const card=$('.case-card');if(!card)return;const gap=19.2;const amount=(card.getBoundingClientRect().width+gap)*casePosition;$('#caseTrack').style.transform=`translateX(${(lang==='ar'?1:-1)*amount}px)`;$('#caseIndex').textContent=`${String(casePosition+1).padStart(2,'0')} / 05`;}
function renderModels(){$('#modelList').innerHTML=models.map((m,i)=>`<article class="model-row"><span class="model-num">${String(i+1).padStart(2,'0')}</span><h3>${m[1][lang]}</h3><p>${m[2][lang]}</p><b>↗</b></article>`).join('');}
function renderOperators(){const pos=[[4,8],[43,2],[68,12],[18,25],[54,28],[1,43],[36,44],[73,48],[15,61],[53,65],[4,79],[35,83],[70,82],[24,95],[60,100],[2,104]];$('#operatorCloud').innerHTML=operators.map((o,i)=>`<span class="operator ${['Ehsan','NCVC','Jood'].includes(o)?'featured':''}" style="left:${pos[i][0]}%;top:${pos[i][1]/1.2}%">${o}</span>`).join('');}
function initEvents(){$('.lang-switch').addEventListener('click',()=>setLanguage(lang==='en'?'ar':'en'));$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;active=b.dataset.filter;visible=12;renderFilters();renderInitiatives();});$('#searchInput').addEventListener('input',()=>{visible=12;renderInitiatives()});$('#clearFilters').addEventListener('click',()=>{active='all';visible=12;$('#searchInput').value='';renderFilters();renderInitiatives()});$('#loadMore').addEventListener('click',()=>{visible+=12;renderInitiatives()});$('#initiativeGrid').addEventListener('click',e=>{const c=e.target.closest('[data-index]');if(c)openDetail(+c.dataset.index)});$$('[data-close-modal]').forEach(x=>x.addEventListener('click',()=>toggleModal('#detailModal',false)));$('#methodBtn').addEventListener('click',()=>toggleModal('#methodModal',true));$$('[data-close-method]').forEach(x=>x.addEventListener('click',()=>toggleModal('#methodModal',false)));$('#casePrev').addEventListener('click',()=>{casePosition=Math.max(0,casePosition-1);moveCases()});$('#caseNext').addEventListener('click',()=>{casePosition=Math.min(cases.length-1,casePosition+1);moveCases()});window.addEventListener('resize',moveCases);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.modal.open').forEach(m=>toggleModal('#'+m.id,false))}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus();document.querySelector('#atlas').scrollIntoView()}});}
function initMotion(){if(!window.gsap)return;gsap.registerPlugin(ScrollTrigger);gsap.from('.hero-title .line>span',{yPercent:115,duration:1.1,stagger:.13,ease:'power4.out',delay:.2});gsap.from('.hero .reveal',{y:30,opacity:0,duration:.8,stagger:.15,ease:'power3.out',delay:.65});gsap.from('.hero-stats article',{y:24,opacity:0,duration:.7,stagger:.09,delay:1,ease:'power2.out'});gsap.to('.orbit-a',{rotation:360,duration:35,repeat:-1,ease:'none'});gsap.to('.orbit-b',{rotation:-360,duration:28,repeat:-1,ease:'none'});gsap.utils.toArray('.statement h2,.section-head h2,.cases-intro h2,.ecosystem h2,.closing h2').forEach(el=>gsap.from(el,{scrollTrigger:{trigger:el,start:'top 86%'},y:60,opacity:0,duration:.9,ease:'power3.out'}));gsap.utils.toArray('.worlds article,.model-row').forEach(el=>gsap.from(el,{scrollTrigger:{trigger:el,start:'top 91%'},y:28,opacity:0,duration:.65,ease:'power2.out'}));gsap.to('.closing-orb',{scrollTrigger:{trigger:'.closing',start:'top bottom',end:'bottom top',scrub:1},yPercent:-30,scale:1.15});gsap.utils.toArray('.operator').forEach((el,i)=>gsap.to(el,{y:i%2?12:-12,x:i%3?5:-5,duration:2.8+i%4*.45,repeat:-1,yoyo:true,ease:'sine.inOut'}));ScrollTrigger.create({start:0,end:'max',onUpdate:s=>$('.progress span').style.width=`${s.progress*100}%`});}
renderFilters();renderInitiatives();renderCases();renderModels();renderOperators();initEvents();setLanguage('en');initMotion();
